name: build_and_push

on: 
  push:
    branches:
      - main

env:
  IMAGE_NAME: souravkuila12345/todo-app
  IMAGE_VERSION: "1.0"

permissions:
  id-token: write
  contents: read

jobs: 
  build:
    name: buildJob
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Build
        working-directory: todo-app
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_VERSION .

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: achinta1
          password: ${{ secrets.DOCKER_PAT }}

      - name: Push image to Docker Hub
        run: |
          docker push $IMAGE_NAME:$IMAGE_VERSION

  deploy:
    name: Deploy App to AKS
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: AKS Login
        run: |
          az aks get-credentials \
            --resource-group ${{ secrets.RG_NAME }} \
            --name ${{ secrets.AKS_NAME }} \
            --overwrite-existing

      - name: Deploy to AKS
        working-directory: manifests
        run: |
          kubectl apply -f deployment.yaml -n todo --validate=false
          kubectl apply -f service.yaml -n todo --validate=false
          kubectl apply -f ingress.yaml -n todo --validate=false
